# Generated by Django 2.1.2 on 2021-06-16 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210616_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
