# Generated by Django 2.1.2 on 2021-06-17 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210616_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '日別情報', 'verbose_name_plural': 'サンプル2'},
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='item',
            name='money',
            field=models.IntegerField(blank=True, null=True, verbose_name='金額'),
        ),
    ]
