# Generated by Django 2.1.2 on 2021-06-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210617_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '日別情報', 'verbose_name_plural': '日別情報'},
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '売上'), (2, '酒'), (3, 'レイ'), (4, 'ヒカル'), (5, 'シン'), (6, '店')], null=True, verbose_name='分類'),
        ),
    ]
