# Generated by Django 2.1.2 on 2021-06-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210617_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '売上'), (2, '酒'), (3, 'レイ'), (4, 'ヒカル'), (5, 'シン'), (6, '店'), (7, '他')], null=True, verbose_name='分類'),
        ),
    ]
